/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.Date;
import Controller.controller;
import Model.registro;
import javax.swing.JOptionPane;


/**
 *
 * @author ESTERBEN
 */
public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);

        AgregarItem();
        controller contro = new controller();
        contro.listarRegistro(jTable_Datos);
        fecha();
        
    }

    public Image getIconImage() {
        Image Logo = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.jpg"));
        return Logo;
    }
    
    public Date fecha() {
        Date date = new Date();
        jDateChooser_Fecha.setDate(date);
        
        return date;
    }
//convierte la fecha de Date a tipo fecha SQL
    public Date Convertirfecha() {
        Date date = jDateChooser_Fecha.getDate();
        long f = date.getTime();
        java.sql.Date fecha = new java.sql.Date(f);
        
        return fecha;
    }
    
    public void Limpiar(){
        
        jTextField_NombreCompleto.setText("");
        jTextField_Cedula.setText("");
        jTextField_Edad.setText("");
        jTextField_Direccion.setText("");
        jTextField_Telefono.setText("");
        jTextField_Profesion.setText("");
        jTextField_Busqueda.setText("");
    }

    public void AgregarItem() {
        jComboBox_Busqueda.addItem("");
        jComboBox_Busqueda.addItem("Fecha");
        jComboBox_Busqueda.addItem("Cedula");
        jComboBox_Busqueda.addItem("Profesion");
        
        jComboBox_Estado.addItem("");
        jComboBox_Estado.addItem("Desempleado");
        jComboBox_Estado.addItem("Laborando");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Fecha = new javax.swing.JLabel();
        jDateChooser_Fecha = new com.toedter.calendar.JDateChooser();
        jLabel_NombreCompleto = new javax.swing.JLabel();
        jTextField_NombreCompleto = new javax.swing.JTextField();
        jLabel_Cedula = new javax.swing.JLabel();
        jTextField_Cedula = new javax.swing.JTextField();
        jLabel_Edad = new javax.swing.JLabel();
        jTextField_Edad = new javax.swing.JTextField();
        jLabel_Telefono = new javax.swing.JLabel();
        jTextField_Telefono = new javax.swing.JTextField();
        jLabel_Direccion = new javax.swing.JLabel();
        jTextField_Direccion = new javax.swing.JTextField();
        jLabel_Profesion = new javax.swing.JLabel();
        jLabel_Estado = new javax.swing.JLabel();
        jTextField_Profesion = new javax.swing.JTextField();
        jComboBox_Estado = new javax.swing.JComboBox<>();
        jButton_Guardar = new javax.swing.JButton();
        jButton_Actualizar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jLabel_TituloRegistrar = new javax.swing.JLabel();
        jLabel_TituloBusqueda = new javax.swing.JLabel();
        jTextField_Busqueda = new javax.swing.JTextField();
        jButton_Busqueda = new javax.swing.JButton();
        jButton_MostrarTabla = new javax.swing.JButton();
        jComboBox_Busqueda = new javax.swing.JComboBox<>();
        jLabel_TituloTabla = new javax.swing.JLabel();
        jScrollPane_TablaPersonas = new javax.swing.JScrollPane();
        jTable_Datos = new javax.swing.JTable();
        jLabel_Imagen = new javax.swing.JLabel();
        jLabel_Fondo = new javax.swing.JLabel();
        jLabel_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Fecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_Fecha.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Fecha.setText("Fecha");
        getContentPane().add(jLabel_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, -1));
        getContentPane().add(jDateChooser_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 200, 20));

        jLabel_NombreCompleto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_NombreCompleto.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_NombreCompleto.setText("Nombre Completo");
        getContentPane().add(jLabel_NombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, -1));

        jTextField_NombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NombreCompletoActionPerformed(evt);
            }
        });
        jTextField_NombreCompleto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NombreCompletoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_NombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 200, -1));

        jLabel_Cedula.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_Cedula.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Cedula.setText("Cedula");
        getContentPane().add(jLabel_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, -1));

        jTextField_Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CedulaKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 200, -1));

        jLabel_Edad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_Edad.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Edad.setText("Edad");
        getContentPane().add(jLabel_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, -1));

        jTextField_Edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_EdadKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 200, -1));

        jLabel_Telefono.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_Telefono.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Telefono.setText("Telefono");
        getContentPane().add(jLabel_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, -1));

        jTextField_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_TelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 200, -1));

        jLabel_Direccion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_Direccion.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Direccion.setText("Dirección");
        getContentPane().add(jLabel_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, -1));
        getContentPane().add(jTextField_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 200, -1));

        jLabel_Profesion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_Profesion.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Profesion.setText("Profesión");
        getContentPane().add(jLabel_Profesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, -1));

        jLabel_Estado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_Estado.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Estado.setText("Estado");
        getContentPane().add(jLabel_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, -1));

        jTextField_Profesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ProfesionKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_Profesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 200, -1));

        getContentPane().add(jComboBox_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 200, -1));

        jButton_Guardar.setBackground(new java.awt.Color(51, 153, 0));
        jButton_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/guardar.png"))); // NOI18N
        jButton_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_GuardarMouseClicked(evt);
            }
        });
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 50, 50));

        jButton_Actualizar.setBackground(new java.awt.Color(0, 153, 153));
        jButton_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/actualizar.png"))); // NOI18N
        jButton_Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ActualizarMouseClicked(evt);
            }
        });
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 50, 50));

        jButton_Eliminar.setBackground(new java.awt.Color(204, 0, 0));
        jButton_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/borrar.png"))); // NOI18N
        jButton_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_EliminarMouseClicked(evt);
            }
        });
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 50, 50));

        jLabel_TituloRegistrar.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel_TituloRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_TituloRegistrar.setText("Registrar Personas");
        getContentPane().add(jLabel_TituloRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 140, -1));

        jLabel_TituloBusqueda.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel_TituloBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_TituloBusqueda.setText("Busqueda");
        getContentPane().add(jLabel_TituloBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        getContentPane().add(jTextField_Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 200, 30));

        jButton_Busqueda.setBackground(new java.awt.Color(247, 176, 8));
        jButton_Busqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        jButton_Busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_BusquedaMouseClicked(evt);
            }
        });
        getContentPane().add(jButton_Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 30, 30));

        jButton_MostrarTabla.setBackground(new java.awt.Color(247, 176, 8));
        jButton_MostrarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/tabla.png"))); // NOI18N
        jButton_MostrarTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_MostrarTablaMouseClicked(evt);
            }
        });
        getContentPane().add(jButton_MostrarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 30, 30));

        jComboBox_Busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_BusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 200, -1));

        jLabel_TituloTabla.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel_TituloTabla.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_TituloTabla.setText("Listado de Personas");
        getContentPane().add(jLabel_TituloTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 150, -1));

        jTable_Datos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable_Datos.setForeground(new java.awt.Color(0, 0, 0));
        jTable_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Datos.setFocusable(false);
        jTable_Datos.getTableHeader().setReorderingAllowed(false);
        jTable_Datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DatosMouseClicked(evt);
            }
        });
        jScrollPane_TablaPersonas.setViewportView(jTable_Datos);

        getContentPane().add(jScrollPane_TablaPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 860, 180));

        jLabel_Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cristo-Rey.jpg"))); // NOI18N
        getContentPane().add(jLabel_Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 310, 420));

        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 650));

        jLabel_id.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NombreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NombreCompletoActionPerformed

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_GuardarActionPerformed

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jButton_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_GuardarMouseClicked
        String fecha = Convertirfecha().toString();
        String nombre_completo = jTextField_NombreCompleto.getText();
        String cedula = jTextField_Cedula.getText();
        int edad = Integer.parseInt(jTextField_Edad.getText());
        String direccion = jTextField_Direccion.getText();
        String telfono = jTextField_Telefono.getText();
        String profesion = jTextField_Profesion.getText();
        String estado = jComboBox_Estado.getSelectedItem().toString();
        //controller
        controller contro = new controller();
        //modelo
        registro registro = new registro(fecha, nombre_completo, cedula, edad, direccion, telfono, profesion, estado);
        contro.crear(registro);
        JOptionPane.showMessageDialog(null, "Se a guardado exitosamente el registro ");
        
        Limpiar();
        controller control = new controller();
        control.listarRegistro(jTable_Datos);
    }//GEN-LAST:event_jButton_GuardarMouseClicked

    private void jComboBox_BusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_BusquedaActionPerformed

    }//GEN-LAST:event_jComboBox_BusquedaActionPerformed

    private void jButton_BusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_BusquedaMouseClicked
       String Datosrecogidos = jTextField_Busqueda.getText();
        controller buscar = new controller();
        if(jComboBox_Busqueda.getSelectedItem() == "Fecha"){
             buscar.listarFechas(jTable_Datos, Datosrecogidos);
                   
        }else if(jComboBox_Busqueda.getSelectedItem() == "Cedula"){
             buscar.listarCedula(jTable_Datos, Datosrecogidos);
                    
        }else if(jComboBox_Busqueda.getSelectedItem() == "Profesion"){
            buscar.listarprofesion(jTable_Datos, Datosrecogidos);
            
        }else{
            JOptionPane.showMessageDialog(null, "Escoja una opcion para realizar la busqueda");
        }

       
    }//GEN-LAST:event_jButton_BusquedaMouseClicked

    private void jButton_ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ActualizarMouseClicked
        int id = Integer.parseInt(jLabel_id.getText());
        String nombre_completo = jTextField_NombreCompleto.getText();
        String cedula = jTextField_Cedula.getText();
        int edad = Integer.parseInt(jTextField_Edad.getText());
        String direccion = jTextField_Direccion.getText();
        String telfono = jTextField_Telefono.getText();
        String profesion = jTextField_Profesion.getText();
        String estado = jComboBox_Estado.getSelectedItem().toString();
        //controlador
        controller update = new controller();
        //clase 
        registro regis = new registro();
        regis.setId(id);
        regis.setNombreCompleta(nombre_completo);
        regis.setCedula(cedula);
        regis.setEdad(edad);
        regis.setDireccion(direccion);
        regis.setTelefono(telfono);
        regis.setProfesion(profesion);
        regis.setEstado(estado);
        update.actualizar(regis);
        
        JOptionPane.showMessageDialog(null,"Se a actualizado exitosamente el registro" );
        controller contro = new controller();
        contro.listarRegistro(jTable_Datos);
        Limpiar();
    }//GEN-LAST:event_jButton_ActualizarMouseClicked

    private void jTable_DatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DatosMouseClicked
         int fila = jTable_Datos.getSelectedRow();
        
            jDateChooser_Fecha.setDateFormatString(jTable_Datos.getValueAt(fila, 1).toString());
            jTextField_NombreCompleto.setText(jTable_Datos.getValueAt(fila, 2).toString());
            jTextField_Cedula.setText(jTable_Datos.getValueAt(fila, 3).toString());
            jTextField_Edad.setText(jTable_Datos.getValueAt(fila, 4).toString());
            jTextField_Direccion.setText(jTable_Datos.getValueAt(fila, 5).toString());
            jTextField_Telefono.setText(jTable_Datos.getValueAt(fila, 6).toString());
            jTextField_Profesion.setText(jTable_Datos.getValueAt(fila, 7).toString());
            jComboBox_Estado.setSelectedItem(jTable_Datos.getValueAt(fila, 8).toString());
            jLabel_id.setText(jTable_Datos.getValueAt(fila, 0).toString());
    }//GEN-LAST:event_jTable_DatosMouseClicked

    private void jButton_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_EliminarMouseClicked
        int id = Integer.parseInt(jLabel_id.getText());
        //controller
        controller delete = new controller();
        //clases
        registro regis = new registro();
        regis.setId(id);
        delete.eliminar(regis);
        controller contro = new controller();
        contro.listarRegistro(jTable_Datos);
        JOptionPane.showMessageDialog(null, "Se a eliminado exitosamente el regitro");
        Limpiar();
    }//GEN-LAST:event_jButton_EliminarMouseClicked

    private void jTextField_TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_TelefonoKeyTyped
        char numero = evt.getKeyChar();
        if (numero < '0' || numero > '9') evt.consume();
    }//GEN-LAST:event_jTextField_TelefonoKeyTyped

    private void jTextField_CedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CedulaKeyTyped
        char numero = evt.getKeyChar();
        if (numero < '0' || numero > '9') evt.consume();
    }//GEN-LAST:event_jTextField_CedulaKeyTyped

    private void jTextField_EdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_EdadKeyTyped
        char numero = evt.getKeyChar();
        if (numero < '0' || numero > '9') evt.consume();
    }//GEN-LAST:event_jTextField_EdadKeyTyped

    private void jTextField_NombreCompletoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NombreCompletoKeyTyped
        char letras = evt.getKeyChar();
        if ((letras < 'a' || letras > 'z') && (letras < 'A' || letras > 'Z' ) && (letras < ' ' || letras > ' ') && (letras < 'ñ' || letras > 'ñ') && (letras < 'Ñ' || letras > 'Ñ')) evt.consume();
    }//GEN-LAST:event_jTextField_NombreCompletoKeyTyped

    private void jTextField_ProfesionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ProfesionKeyTyped
        char letras = evt.getKeyChar();
        if ((letras < 'a' || letras > 'z') && (letras < 'A' || letras > 'Z' ) && (letras < ' ' || letras > ' ') && (letras < 'ñ' || letras > 'ñ') && (letras < 'Ñ' || letras > 'Ñ')) evt.consume();
    }//GEN-LAST:event_jTextField_ProfesionKeyTyped

    private void jButton_MostrarTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_MostrarTablaMouseClicked
        controller contro = new controller();
        contro.listarRegistro(jTable_Datos);
        Limpiar();
    }//GEN-LAST:event_jButton_MostrarTablaMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_Busqueda;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JButton jButton_MostrarTabla;
    private javax.swing.JComboBox<String> jComboBox_Busqueda;
    private javax.swing.JComboBox<String> jComboBox_Estado;
    private com.toedter.calendar.JDateChooser jDateChooser_Fecha;
    private javax.swing.JLabel jLabel_Cedula;
    private javax.swing.JLabel jLabel_Direccion;
    private javax.swing.JLabel jLabel_Edad;
    private javax.swing.JLabel jLabel_Estado;
    private javax.swing.JLabel jLabel_Fecha;
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JLabel jLabel_Imagen;
    private javax.swing.JLabel jLabel_NombreCompleto;
    private javax.swing.JLabel jLabel_Profesion;
    private javax.swing.JLabel jLabel_Telefono;
    private javax.swing.JLabel jLabel_TituloBusqueda;
    private javax.swing.JLabel jLabel_TituloRegistrar;
    private javax.swing.JLabel jLabel_TituloTabla;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JScrollPane jScrollPane_TablaPersonas;
    private javax.swing.JTable jTable_Datos;
    private javax.swing.JTextField jTextField_Busqueda;
    private javax.swing.JTextField jTextField_Cedula;
    private javax.swing.JTextField jTextField_Direccion;
    private javax.swing.JTextField jTextField_Edad;
    private javax.swing.JTextField jTextField_NombreCompleto;
    private javax.swing.JTextField jTextField_Profesion;
    private javax.swing.JTextField jTextField_Telefono;
    // End of variables declaration//GEN-END:variables
}
